# Default values for galaxy-postgres-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
image: ghcr.io/cloudnative-pg/postgresql:17.2

#- The number of Postgres instances in the cluster
instances: 1

operator:
  #- Should the operator be deployed?
  deploy: false

#- Configure backing up to a Cloud bucket using BarMan. See https://cloudnative-pg.io/documentation/current/backup_barmanobjectstore/
backup:
  enabled: true
  #- The name of the bucket to use for backups
  bucket: gs://ks-anvil-bucket
  #- The credentials to use for the bucket. The credentials provided will depend on the cloud provider.  This is an
  #- example for using a Google bucket from a GKE cluster.
  credentials:
    googleCredentials:
      gkeEnvironment: true

#- When set to true the cluster will be restored from the latest backup rather
#- bootstrapping the cluster from scratch.
recovery: false

#- The database configuration
database:
  owner: galaxydbuser
  name: galaxy
  password: galaxypassword

postgresql:
  #- The name of the Postgres user to use for the database
  username: postgres
  #- The password for the Postgres user. If not specified a random password will be generated
  password: postgres

#- Configuration for the persistent volume
persistence:
  size: 10Gi
  storageClassName: "standard"
  #- Configuration to use an existing persistent disk. If omitted it is
  #- assumed the storage class can dynamically provision storage.
  disk:
    #- The volumeHandle for the persistent disk
    handle: "projects/anvil-and-terra-development/zones/us-east1-b/disks/ks-postgres-pd"
    fsType: "ext4"
    #- See your cloud provider documentation for the correct CSI driver to use
    driver: pd.csi.storage.gke.io

#- The configuration the pgcluster will use to define its PVC
storage:
  size: 10Gi
  accessModes:
    - ReadWriteOnce
