# Default values for galaxy-postgres-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
image: ghcr.io/cloudnative-pg/postgresql:17.2

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
instances: 1
bootstrap: true
operator:
  deploy: false

backup:
  enabled: true
  bucket: gs://ks-anvil-bucket
  credentials:
    googleCredentials:
      gkeEnvironment: true

recovery: false

database:
  owner: galaxydbuser
  name: galaxy
  password: galaxypassword

postgresql:
  username: postgres
  password: postgres

persistence:
  size: 10Gi
  storageClassName: "standard"
  disk:
    handle: "projects/anvil-and-terra-development/zones/us-east1-b/disks/ks-postgres-pd"
    fsType: "ext4"
    driver: pd.csi.storage.gke.io

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/

storage:
  size: 10Gi
  accessModes:
    - ReadWriteOnce

#
##This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
#serviceAccount:
#  # Specifies whether a service account should be created
#  create: true
#  # Automatically mount a ServiceAccount's API credentials?
#  automount: true
#  # Annotations to add to the service account
#  annotations: {}
#  # The name of the service account to use.
#  # If not set and create is true, a name is generated using the fullname template
#  name: ""
