---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "galaxy-postgres-helm.pv" . }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- if .Values.persistence.disk }}
  csi:
    driver: {{ default "pd.csi.storage.gke.io" .Values.persistence.disk.driver }}
    fsType: {{ default "ext4" .Values.persistence.disk.fsType }}
    volumeHandle: "projects/anvil-and-terra-development/zones/us-east1-b/disks/ks-postgres-pd"
  {{- end }}
