apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ include "galaxy-postgres-helm.postgres-credentials" . }}
  labels:
    {{- include "galaxy-postgres-helm.labels" . | nindent 4 }}
data:
  username: {{ printf "%s" .Values.postgresql.username | b64enc | quote }}
  password: {{ default (randAlphaNum 16) .Values.postgresql.password | b64enc | quote }}
