{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingDatabase) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ include "galaxy-postgres-helm.galaxy-credentials" . }}
  labels:
    {{- include "galaxy-postgres-helm.labels" . | nindent 4 }}
data:
  username: {{ .Values.database.owner | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
{{- end }}
